### ISSUE TITLE
Social Shares removed when installing HTTPS 

### ISSUE THREAD

**Issue by markfloyd10** [copyblogger/genesis-simple-share#89]
Just Installed https in compliance to google and now Social Shares for Simple Share have been removed. I have looked all over and can not find anything to fixed the issue.

**Comment by NicktheGeek** [comment]
Thanks for checking. Unfortunately the services reporting the social counts see http and https urls as different shares. This means switching to https is like changing the page urls for your entire site as far as social services are concerned. 

We have been looking at options to try and make it work for both http and https under #76. Since we have that open I'm going to close this as a duplicate.

**Comment by NicktheGeek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Genesis Simple Share](https://trello.com/c/p4ZJkg29/10-genesis-simple-share)
